replicaCount: 1

image:
  repository: registry.gitlab.com/goltruck/web/development
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - goltruck.com
  tls:
    - secretName: goltruck-web-tls-cert
      hosts:
        - goltruck.com

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   # cpu: 100m
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
