apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: gitlab-web-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "goltruck-web.name" . }}
    chart: {{ template "goltruck-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiZ2l0bGFiK2RlcGxveS10b2tlbi03OTE1IiwicGFzc3dvcmQiOiJtSlRMdjF0ODExM0dGd1E0RXA3YyIsImVtYWlsIjoibWFpbEBtYWlsLmNvbSIsImF1dGgiOiJaMmwwYkdGaUsyUmxjR3h2ZVMxMGIydGxiaTAzT1RFMU9tMUtWRXgyTVhRNE1URXpSMFozVVRSRmNEZGoifX19Cg==
