export const cell: string;
export const containerCount: string;
export const countInput: string;
export const inputContainer: string;
export const container__deleteButton: string;
export const containers__lastTableCell: string;
export const row: string;
export const row__cell: string;
export const row__cellValue: string;
